[package]
name = "kiln-rs"
version = "0.1.0"
authors = ["Brian <neumaics@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "*"
actix-web = "3"
actix-web-actors = "3"
rsfuzzy = { git = "https://github.com/auseckas/rsfuzzy" }
rand = "0.7"
tracing = "0.1"
tracing-subscriber = "0.2"
serde = "1.0"
serde_yaml = "0.8"